name: PR Insights ğŸ“

on:
  workflow_call:

jobs:
  dvc-feature-flag-insights:
    runs-on: ubuntu-latest
    name: Generate DevCycle PR Insights ğŸ“
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: DevCycleHQ/feature-flag-pr-insights-action@v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-key: ${{ secrets.DVC_PROJECT_KEY }}
          client-id: ${{ secrets.DVC_CLIENT_ID }}
          client-secret: ${{ secrets.DVC_CLIENT_SECRET }}
