name: fix code styling âœ¨

on:
  workflow_call:
    inputs:
      php:
        default: "8.1"
        type: string
      message:
        default: Fix code styling
        type: string
      fix:
        default: true
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ“
        uses: actions/checkout@v4

      - name: Setup PHP ğŸ‘¨â€ğŸ’»
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint ğŸŒŸ
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit linted files âœ¨
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.message }}